### ISSUE TITLE
Migrate to EsLint

### ISSUE THREAD

**Issue by wischli** [KILTprotocol/sdk-js#132]
As TsLint [will be deprecated throughout this year](https://github.com/palantir/tslint/issues/4534) in favor of `typescript-eslint`, I would recommend to [move to EsLint](https://blog.matterhorn.dev/posts/learn-typescript-linting-part-1/) instead, or at least keep the migration in mind. See [here](https://github.com/typescript-eslint/typescript-eslint) for more information.

**Comment by tjwelde** [comment]
Thank you for the information. I was never a big fan of tslint, especially since I was missing some eslint react rules. We will move over to it soon.
