### ISSUE TITLE
Wrong parameter description in code documentation

### ISSUE THREAD

**Issue by martines3000** [KILTprotocol/sdk-js#459]
While building a demo app with your SDK, I found a couple of places where the documentation wasn't updated when the corresponding code changed. 
It's mainly where you changed ` IPublicIdentity['address']` to `IDidDetails['did']`.

Code snippets:

https://github.com/KILTprotocol/sdk-js/blob/15350115a3aaf04f51e7ad752060c44a8aad13e4/packages/core/src/claim/Claim.ts#L94-L119

https://github.com/KILTprotocol/sdk-js/blob/15350115a3aaf04f51e7ad752060c44a8aad13e4/packages/core/src/claim/Claim.ts#L61-L92

https://github.com/KILTprotocol/sdk-js/blob/15350115a3aaf04f51e7ad752060c44a8aad13e4/packages/messaging/src/Message.ts#L206-L227

I will also make a PR with potential fixes.

**Comment by Diiaablo95** [comment]
Hello. We are aware of the issue, and there is a DID overhaul upcoming which takes care, among other things, to fix all these small type definition inconsistencies. Sorry for the inconvenience.
