### ISSUE TITLE
Unable to create new Ctype: createType(StorageEntryTypeLatest):: Invalid character

### ISSUE THREAD

**Issue by vpapanchev** [KILTprotocol/sdk-js#484]
Hello,

I am just starting to learn how to use the SDK and encountered the following error while following the [KILT Workshop](https://dev.kilt.io/docs/sdk/workshop/welcome/).

Error while checking on chain ctype Error: **createType(StorageEntryTypeLatest):: Invalid character**

Here is the complete output of executing attester/generateCtype.js:

```
:~/ssi-workspace/kilt_project$ node attester/generateCtype.js

@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 8.3.3       /home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/util-crypto/node_modules/@polkadot/util/
        esm 8.4.1       /home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/util/
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 8.3.3       /home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/util-crypto/
        esm 8.4.1       /home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/keyring/node_modules/@polkadot/util-crypto/
Applied changes: logLevel=Error to log groups 'all'.
Applied changes: logLevel=Error to log groups 'all'.
Error while checking on chain ctype Error: createType(StorageEntryTypeLatest):: Invalid character
    at createTypeUnsafe (file:///home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/types/create/createType.js:57:18)
    at TypeRegistry.createTypeUnsafe (file:///home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/types/create/registry.js:375:12)
    at TypeRegistry.createType (file:///home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/types/create/registry.js:367:17)
    at extendHeadMeta (file:///home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.js:141:20)
    at extendPrefixedMap (file:///home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.js:159:23)
    at createFunction (file:///home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.js:193:5)
    at file:///home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/types/metadata/decorate/storage/index.js:46:25
    at Object.get [as did] (file:///home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/util/lazy.js:20:17)
    at file:///home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/api/base/Decorate.js:444:236
    at Object.get [as did] (file:///home/papanchev/ssi-workspace/kilt_project/node_modules/@polkadot/util/lazy.js:20:17)
```

Has someone ever encountered this issue?
I am very new to both KILT and Polkadot and got very lost while searching for a solution.
I have been following the workshop without any changes.

Also, everytime I run something, I get the warning about the conflicting versions.

Cheers,
Vasil

**Comment by Diiaablo95** [comment]
Hello, this is due to issues with our dependencies on the polkadot SDK.
There will be a new release candidate of the KILT SDK either today or on Monday, that fixes also this issue. I will ping you here when the new release candidate is out. Thanks for the patience.

**Comment by Diiaablo95** [comment]
Hello @vpapanchev! We have published a new release candidate, which will most likely be promoted to official release (with `latest` tag), early next week. Please try it out https://www.npmjs.com/package/@kiltprotocol/sdk-js/v/0.26.0-rc.4, and please let me know if you face other issues with it 😊 We will update the workshop instructions as soon as the new official release is out.

**Comment by vpapanchev** [comment]
Hello @Diiaablo95! Thanks for the timely replies. I have tried out the new release and went through the [Getting Started Guide](https://github.com/kiltprotocol/sdk-js/blob/HEAD/docs/getting-started.md) using the Peregrine test-network. 
Everything seems to be working well.

**Comment by Diiaablo95** [comment]
Perfect. Closing the issue then. If you happen to have the same problem again, feel free to re-open.
