### ISSUE TITLE
Enable extrinsic authorization with Sporran

### ISSUE THREAD

**Issue by gdethier** [KILTprotocol/sdk-js#583]
When authorizing an extrinsic there should be some documented method to do so using the [Sporran extension](https://github.com/BTE-Trusted-Entity/sporran-extension).

Current examples look like this in the documentation and imply the use of a [demo keystore](https://github.com/KILTprotocol/sdk-js/blob/0.28.0/packages/did/src/DemoKeystore/DemoKeystore.ts).
```typescript
const extrinsic = await attesterFullDid.authorizeExtrinsic(
    tx as unknown as Extrinsic,
    demoKeystore,
    attesterAccountAddress
);
```

It would be nice to be able to directly inject the Sporran extension in place of the demoKeystore.

**Comment by tjwelde** [comment]
Thanks for the suggestion. The SDK is being overhauled and we are planning to make a library for easier sporran <-> dApp integration, which should solve this issue.
We already removed the necessity to have a Keystore, so this is just a callback now. Is that sufficient?

**Comment by ntn-x2** [comment]
Hey @gdethier. Can we move on and close this issue? Or do you still have problems?

**Comment by gdethier** [comment]
@ntn-x2 No problem anymore, you can close this issue. Thanks!
