### ISSUE TITLE
Error while upgrading lightDID to fullDID

### ISSUE THREAD

**Issue by thewoodfish** [KILTprotocol/sdk-js#695]
```// Generate the DID migration tx.

  const migrationTx = await Kilt.Did.getStoreTx(
    lightDid,
    submitterAccount.address,
    signCallback
  )
 ```

The function `getStoreTx` is used when performing the upgrade. The issue i noticed is that i created a light did with an authentication field.

`{
  uri: 'did:kilt:light:004qECRa2Y9p5SsC3MmHE33S5wjoYz5ud4wVMQNkYNMJgAgzvy:z121u5VHr14uLtZS39x1WTD5kyEno9vZfVVwKX3Z2jTxwkqAM1W12kovc5uddXcVqveEGG5PwfYa7EWq4jkxtEXWuM9LtYifGB32i5Be1jhAuiLprxVTgFNGpMydKoLPeVd5ZNnmngu6LNmBLJAUnGyGJF2H9k6YiB7k3RdsXAhEHgkc98FyetBmC4hTZryCqRZUbEU8FgEpw',
  authentication: [ { id: '#authentication', type: 'sr25519', publicKey: [Object] } ],
  service: [ { id: '#claims-repo', type: [Array], serviceEndpoint: [Array] } ]
}
`
The `getStoreTx` function calls the `getAddressByKey` function, passing in the `authentication` field. Since the `authentication` object has a field `type` whose value is 'sr25519', according to the function, the `publicKey` is passed into the `encodeAddress` function. 

Normally in my own understanding this functions signature is the below:
`encodeAddress(key: string | Uint8Array, ss58Format?: 38 | undefined): '4${string}` , meaning it doesn't take an object parameter, which is being passed to it. here

Anyways, the conclusion is that , it is in this function that the program fails. It's all boilerplate, i don't know what to do now. Please help, Thank you.

This is the specific error logged:

```
file:///Users/explorer/Public/samaritan-2nd-wave/node_modules/@polkadot/util-crypto/address/decode.js:29
    throw new Error('Decoding ${encoded}: ${error.message}');
          ^

Error: Decoding [object Object]: Expected non-null, non-empty base58 string input
    at decodeAddress (file:///Users/explorer/Public/samaritan-2nd-wave/node_modules/@polkadot/util-crypto/address/decode.js:29:11)
    at encodeAddress (file:///Users/explorer/Public/samaritan-2nd-wave/node_modules/@polkadot/util-crypto/address/encode.js:12:15)
    at getAddressByKey (file:///Users/explorer/Public/samaritan-2nd-wave/node_modules/@kiltprotocol/did/lib/esm/Did.utils.js:109:21)
    at Module.getStoreTx (file:///Users/explorer/Public/samaritan-2nd-wave/node_modules/@kiltprotocol/did/lib/esm/Did.chain.js:226:17)
    at Module.upgradeToFullDID (file:///Users/explorer/Public/samaritan-2nd-wave/kilt.js:55:40)
    at createKiltCtype (file:///Users/explorer/Public/samaritan-2nd-wave/app.js:758:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.0.0
[nodemon] app crashed - waiting for file changes before starting...


```

**Comment by ntn-x2** [comment]
Hi. The errors mentions something about decoding, not encoding. I am not sure the error is related to what you have presented here. 
The `getAddressByKey` function that you mention, destructures the input into two different variables, `publicKey` and `type`. And it then only uses the `publicKey` to internally call `encodeAddress`. 
Plus, we test all the code snippets that we show in the documentation, and never faced such an issue. I would be interested in seeing a bit more of the code snippet.

**Comment by rflechtner** [comment]
closing as stale, feel free to reopen if this continues to be an issue
