### ISSUE TITLE
Decode issue with polkadot js and chain types definition 

### ISSUE THREAD

**Issue by jiqiang90** [KILTprotocol/sdk-js#701]
Hi , for block 156 seems having decode issue for extrinsic, please see, https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fspiritnet.api.onfinality.io%2Fpublic-ws#/explorer/query/156

Polkadot version 9.11.1

Also we try to inject types from @kiltprotocol/type-definitions still got same error, please help 

```
import { typesBundle } from "@kiltprotocol/type-definitions";

```

**Comment by ntn-x2** [comment]
Hi @jiqiang90, are all versions of @polkadot library the same? Including types-codec? We have already fixed all block parsing once, and we have not changed anything since then, so we are very confident it is an error in one of the underlying @polkadot libraries. Can you please confirm that by, e.g., updating to the latest version available?

**Comment by jamesbayly** [comment]
@ntn-x2  you can see this issue with your offically published libraries provided to PolkadotJS here https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fspiritnet.api.onfinality.io%2Fpublic-ws#/explorer/query/156

We use the same definitions in SubQuery

**Comment by rflechtner** [comment]
I think we may not have released all the fixes made up until now. With v0.31.0 of the type-definitions I can decode this block successfully in the polkadot apps (it's already on their master branch, their next release will finally solve this in the hosted version too). Let me know if that works for you!

**Comment by rflechtner** [comment]
> @ntn-x2 you can see this issue with your offically published libraries provided to PolkadotJS here https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fspiritnet.api.onfinality.io%2Fpublic-ws#/explorer/query/156

This fix is now deployed to the released and hosted version of the polkadot apps, clicking this link show it's working. Closing this issue now, feel free to reopen if you still see some issues.
