### ISSUE TITLE
`@polkadot/api` versions > 51.x inhibits working with a linked sdk

### ISSUE THREAD

**Issue by foby** [KILTprotocol/sdk-js#83]
Reason: client crashes due to check `assertSingletonPackage('@polkadot/keyring')` in https://github.com/polkadot-js/common/blob/master/packages/keyring/src/index.ts

Seems `@polkadot/keyring` is imported multiple times when sdk is linked to client through `yarn link`. Singleton package assertion not a good approach, imo. Should be ensured during compile time not during runtime.

Question: why don't they `export` the `Keyring` instance, which would ensure making it a Singleton?

**Comment by flechtnergalani** [comment]
Closing this as it may be a little outdated. We are on 0.96 now and linking sdk builds with `yalc` works just fine. `yarn link` cannot be used to link the sdk with the demo-client at the moment for unknown reasons, we suggest sticking to `yalc` in all cases.
